name: africulture
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  google_sign_in: ^5.4.2
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  firebase_storage: ^12.4.9
  http: ^1.4.0
  geolocator: ^14.0.2
  cloud_firestore: 5.6.11
  flutter_launcher_icons: ^0.14.4
  percent_indicator: ^4.2.5
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  provider: ^6.1.1
  url_launcher: ^6.1.11
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_app_check: 0.3.2+9
  mqtt_client: ^10.10.0
  flutter_local_notifications: ^19.3.1
  charts_flutter: ^0.12.0
  flutter_spinkit: ^5.2.1
  tflite_flutter: ^0.11.0
  lottie: ^3.3.1
  path: ^1.9.1
  cupertino_icons: ^1.0.8
  icons_launcher: ^3.0.1
  flutter_dotenv: ^5.2.1
  flutter_tts: ^4.2.3
  speech_to_text: 7.0.0
  google_maps_flutter: ^2.2.3
  geocoding: ^2.0.5
  weather_icons: ^3.0.0
  flutter_translate: ^4.0.3
  share_plus: ^11.0.0
  cached_network_image: ^3.4.1
  cloud_functions: ^5.6.2
  photo_view: ^0.14.0
  video_player: ^2.10.0
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.4.9
  fl_chart: ^0.65.0
  webfeed_revised: ^0.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/back_images/
    - .env
    - assets/animations/typing.json
    - assets/animations/plant_grow.json
    - assets/vehicles/motorcycle.jpg
    - assets/vehicles/pickup_truck.jpg
    - assets/vehicles/refrigerated_van.jpg
    - assets/vehicles/tractor_trailer.jpg
    - assets/back_images/weather_background.jpg
    - assets/locale/
    - assets/icon_s/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

dependency_overrides:
  intl: ^0.17.0