final Map<String, Map<String, List<String>>> kenyaLocations = {
  'Baringo': {
    'Baringo Central': [
      'Kabarnet',
      'Sacho',
      'Tenges',
      'Ewalel/Chapchap',
      'Kapropita',
    ],
    'Baringo North': [
      'Barwessa',
      'Kabartonjo',
      'Saimo/Kipsaraman',
      'Saimo/Soi',
      'Bartabwa',
    ],
    'Baringo South': ['Marigat', 'Ilchamus', 'Mochongoi', 'Mukutani'],
    'Eldama Ravine': [
      'Lembus',
      'Lembus Kwen',
      'Ravine',
      'Mumberes/Maji Mazuri',
      'Lembus/Perkerra',
    ],
    'Mogotio': ['Mogotio', 'Emining', 'Kisanana'],
    'Tiaty': [
      'Tirioko',
      'Kolowa',
      'Ribkwo',
      'Silale',
      'Loiyamorock',
      'Tangulbei/Korossi',
      'Churo/Amaya',
    ],
  },
  'Bomet': {
    'Bomet Central': [
      'Chesoen',
      'Ndaraweta',
      'Singorwet',
      'Chilchila',
      'Mutarakwa',
    ],
    'Bomet East': ['Merigi', 'Kembu', 'Longisa', 'Kipreres', 'Chemaner'],
    'Chepalungu': ['Nyangores', 'Sigor', 'Chebunyo', 'Siongiroi'],
    'Konoin': ['Chepchabas', 'Kimulot', 'Mogogosiek', 'Boito', 'Embomos'],
    'Sotik': [
      'Ndanai/Abosi',
      'Chemagel',
      'Kipsonoi',
      'Kapletundo',
      'Rongena/Manaret',
    ],
  },
  'Bungoma': {
    'Bumula': [
      'South Bukusu',
      'Bumula',
      'Khasoko',
      'Kabula',
      'Kimaeti',
      'West Bukusu',
      'Siboti',
    ],
    'Kabuchai': ['Kabuchai/Chwele', 'West Nalondo', 'Bwake/Luuya', 'Mukuyuni'],
    'Kanduyi': [
      'Bukembe West',
      'Bukembe East',
      'Township',
      'Khalaba',
      'Musikoma',
      'East Sang’alo',
      'Marakaru/Tuuti',
      'West Sang’alo',
    ],
    'Kimilil': ['Kimilili', 'Kibingei', 'Maeni', 'Kibisi'],
    'Mt Elgon': [
      'Cheptais',
      'Chesikaki',
      'Chepyuk',
      'Kapkateny',
      'Kaptama',
      'Elgon',
    ],
    'Sirisia': ['Namwela', 'Malakisi/South Kulisiru', 'Lwandanyi'],
    'Tongaren': [
      'Milima',
      'Ndalu/Tabani',
      'Tongaren',
      'Soysambu/Mitua',
      'Naitiri/Kabuyefwe',
      'Mbakalo',
    ],
    'Webuye East': ['Mihuu', 'Ndivisi', 'Maraka'],
    'Webuye West': ['Sitikho', 'Matulo', 'Bokoli'],
  },
  'Busia': {
    'Budalangi': [
      'Bunyala Central',
      'Bunyala North',
      'Bunyala West',
      'Bunyala South',
    ],
    'Butula': [
      'Marachi West',
      'Kingandole',
      'Marachi Central',
      'Marachi East',
      'Marachi North',
      'Elugulu',
    ],
    'Funyula': ['Namboboto/Nambuku', 'Nangina', 'Ageng’a Nanguba', 'Bwiri'],
    'Nambele': ['Bukhayo West', 'Bukhayo East', 'Bukhayo Central'],
    'Teso North': [
      'Malaba Central',
      'Malaba North',
      'Angurai South',
      'Angurai North',
      'Angurai East',
      'Malaba South',
    ],
    'Teso South': [
      'Ang’orom',
      'Chakol South',
      'Chakol North',
      'Amukura West',
      'Amukura East',
      'Amukura Central',
    ],
  },
  'Elgeyo-Marakwet': {
    'Keiyo North': ['Emsoo', 'Kamariny', 'Kapchemutwa', 'Tambach'],
    'Keiyo South': [
      'Metkei',
      'Kaptarakwa',
      'Sengwer',
      'Chepkorio',
      'Soy North',
      'Soy South',
    ],
    'Marakwet East': ['Kapyego', 'Sambirir', 'Endo', 'Embobut/Embolot'],
    'Marakwet West': [
      'Lelan',
      'Sengwer',
      'Cherang’any/Chebororwa',
      'Moiben/Kuserwo',
      'Kapsowar',
      'Arror',
    ],
  },

  'Embu': {
    'Manyatta': [
      'Ruguru-Ngandori',
      'Kithimu',
      'Nginda',
      'Mbeti North',
      'Kirimari',
      'Gaturi South',
    ],
    'Mbeere North': ['Nthawa', 'Muminji', 'Evurore'],
    'Mbeere South': ['Mwea', 'Makima', 'Mbeti South', 'Mavuria', 'Kiambere'],
    'Runyenjes': [
      'Gaturi North',
      'Kagari South',
      'Central',
      'Kagari North',
      'Kyeni North',
      'Kyeni South',
    ],
  },
  'Garissa': {
    'Daadab': ['Dertu', 'Daadab', 'Labisgale', 'Damajale', 'Liboi', 'Abakaile'],
    'Fafi': ['Bura', 'Dekaharia', 'Jarajila', 'Fafi', 'Nanighi'],
    'Ijara': ['Hulugho', 'Sangailu', 'Ijara', 'Masalani'],
    'Lagdera': [
      'Modogashe',
      'Benane',
      'Goreale',
      'Maalamin',
      'Sebena',
      'Baraki',
    ],
    'Balambala': ['Balambala', 'Danyere', 'Jarajara', 'Saka', 'Sankuri'],
    'Dujis': ['Waberi', 'Galbet', 'Township', 'Iftin'],
  },
  'Homa Bay': {
    'Homabay Town': [
      'Homa Bay Central',
      'Homa Bay Arujo',
      'Homa Bay West',
      'Homa Bay East',
    ],
    'Kabondo': ['Kabondo East', 'Kabondo West'],
    'Karachwonyo': [
      'Kibiri',
      'Kokwanyo/Kakelo',
      'Kokwanyo East',
      'Wangchieng',
      'West Karachuonyo',
      'North Karachuonyo',
    ],
    'Kasipul': [
      'West Kasipul',
      'South Kasipul',
      'Central Kasipul',
      'East Kamagak',
      'West Kamagak',
    ],
    'Mbita': [
      'Mfangano Island',
      'Rusinga Island',
      'Lambwe',
      'Kasgunga',
      'Gembe',
      'Gwassi South',
      'Gwassi North',
    ],
    'Ndhiwa': [
      'Kwabwai',
      'Kanyamwa Kosewe',
      'Kanyamwa Kologi',
      'Kabuoch North',
      'Kabuoch South/Pala',
      'Kanyidoto',
      'Kanyikela',
      'Kachieng',
    ],
    'Rangwe': ['West Kagan', 'East Kagan', 'Kochia', 'Kochia North'],
    'Suba': ['Gwassi South', 'Gwassi North', 'Ruma-Kaksingri'],
  },
  'Isiolo': {
    'Isiolo North': [
      'Wahera',
      'Bulla Pesa',
      'Chari',
      'Cherab',
      'Ngare Mara',
      'Burat',
      'Oldonyiro',
    ],
    'Isiolo South': ['Garba Tulla', 'Kinna', 'Sericho'],
  },
  'Kajiado': {
    'Isinya': ['Isinya', 'Kaputiei North', 'Kitengela'],
    'Kajiado Central': ['Purko', 'Matapato North', 'Matapato South'],
    'Kajiado North': [
      'Ongata Rongai',
      'Nkaimurunya',
      'Oloolua',
      'Ngong',
      'Karen',
    ],
    'Loitokitok': [
      'Kimana',
      'Entonet/Lenkisim',
      'Imbirikani/Eselenkei',
      'Kuku',
      'Rombo',
    ],
    'Mashuuru': ['Mashuuru', 'Kenyawa-Poka', 'Imaroro'],
  },
  'Kakamega': {
    'Butere': ['Marama Central', 'Marama West', 'Marama North', 'Marama South'],
    'Kakamega Central': [
      'Murhanda',
      'Butsotso East',
      'Butsotso South',
      'Butsotso Central',
    ],
    'Kakamega East': [
      'Shirere',
      'Shinoyi-Shikomari-Esumeyia',
      'Khalaba',
      'Lurambi',
    ],
    'Kakamega North': ['Malava', 'West Kabras', 'East Kabras', 'South Kabras'],
    'Kakamega South': [
      'Ikolomani South',
      'Ikolomani North',
      'Ikolomani Central',
    ],
    'Khwisero': ['Kisa North', 'Kisa East', 'Kisa West', 'Kisa Central'],
    'Lugari': [
      'Mautuma',
      'Lugari',
      'Lumakanda',
      'Chekalini',
      'Chevaywa',
      'Lwandeti',
    ],
    'Lukuyani': ['South Kabras', 'West Kabras', 'East Kabras'],
    'Lurambi': ['Butsotso South', 'Butsotso East', 'Butsotso Central'],
    'Matete': ['Matete', 'Magadi'],
    'Mumias': ['Mumias North', 'Mumias East', 'Mumias Central', 'Mumias West'],
    'Mutungu': [
      'Isukha North',
      'Isukha Central',
      'Isukha East',
      'Isukha South',
      'Isukha West',
      'Isukha North-East',
    ],
    'Navakholo': [
      'Ingotse-Matiha',
      'Bunyala West',
      'Bunyala East',
      'Bunyala Central',
    ],
  },
  'Kericho': {
    'Ainamoi': [
      'Ainamoi',
      'Kapsoit',
      'Kapkugerwet',
      'Kipchebor',
      'Kipchimchim',
      'Kipkelion',
    ],
    'Belgut': [
      'Waldai',
      'Kabianga',
      'Cheptororiet/Seretut',
      'Kapsuser',
      'Chaik',
    ],
    'Bureti': [
      'Kisiara',
      'Chemosot',
      'Litein',
      'Cheplanget',
      'Kapkatet',
      'Roret',
    ],
    'Kipkelion East': [
      'Londiani',
      'Kedowa/Kimugul',
      'Chepseon',
      'Tendeno/Sorget',
    ],
    'Kipkelion West': ['Kapchebor', 'Kunyak', 'Kamasian', 'Kipkelion'],
    'Soin/Sigowet': ['Kaplelartet', 'Soliat', 'Sigowet', 'Kaplelartet East'],
  },
  'Kiambu': {
    'Gatundu North': ['Gituamba', 'Githobokoni', 'Chania', 'Mang’u'],
    'Gatundu South': ['Kiamwangi', 'Kiganjo', 'Ndarugo', 'Ngenda'],
    'Githunguri': ['Githunguri', 'Githiga', 'Ikinu', 'Ngewa', 'Komothai'],
    'Juja': ['Murera', 'Theta', 'Juja', 'Witethie', 'Kalimoni'],
    'Kabete': ['Kabete', 'Nyathuna', 'Muguga', 'Kanyariri', 'Uthiru'],
    'Kiambaa': ['Muchatha', 'Karuri', 'Ndenderu', 'Kihara'],
    'Kiambu': ['Ting’ang’a', 'Ndumberi', 'Riabai', 'Township'],
    'Kikuyu': ['Kikuyu', 'Sigona', 'Karai', 'Nachu'],
    'Limuru': [
      'Limuru Central',
      'Ndeiya',
      'Bibirioni',
      'Limuru East',
      'Limuru West',
    ],
    'Ruiru': [
      'Gitothua',
      'Biashara',
      'Gatongora',
      'Kahawa Sukari',
      'Kahawa Wendani',
      'Kiuu',
      'Mwiki',
      'Mwihoko',
    ],
    'Thika Town': ['Township', 'Kamenu', 'Hospital', 'Gatuanyaga', 'Ngoliba'],
    'Lari': ['Kambaa', 'Kijabe', 'Nyanduma', 'Kamburu', 'Matathia'],
  },
  'Kilifi': {
    'Ganze': ['Dungicha', 'Bamba', 'Jaribuni', 'Sokoke'],
    'Kaloleni': ['Mariakani', 'Kayafungo', 'Kaloleni', 'Mwanamwinga'],
    'Kilifi North': [
      'Tezo',
      'Sokoni',
      'Kibarani',
      'Dabaso',
      'Matsangoni',
      'Watamu',
      'Mnarani',
    ],
    'Kilifi South': [
      'Junju',
      'Mwarakaya',
      'Shimo La Tewa',
      'Chasimba',
      'Mtepeni',
    ],
    'Magarini': ['Marafa', 'Magarini', 'Gongoni'],
    'Malindi': ['Jilore', 'Kakuyuni', 'Ganda', 'Malindi Town', 'Shella'],
    'Rabai': ['Mwawesa', 'Ruruma', 'Jibana', 'Rabai/Kisurutini'],
  },
  'Kirinyaga': {
    'Kirinyaga Central': ['Mutira', 'Kanyekini', 'Kerugoya', 'Inoi'],
    'Kirinyaga East': ['Kabare', 'Ngariama', 'Baragwi'],
    'Kirinyaga West': ['Kiine', 'Kariti'],
    'Mwea East': [
      'Mutithi',
      'Kangai',
      'Thiba',
      'Wamumu',
      'Nyangati',
      'Murinduko',
      'Gathigiriri',
      'Tebere',
    ],
    'Mwea West': ['Wamumu', 'Kangai', 'Mutithi'],
  },
  'Kisii': {
    'Bonchari': ['Riana', 'Bomorenda', 'Bogiakumu', 'Bomariba'],
    'Kitutu Chache North': ['Monyerero', 'Sensi', 'Marani', 'Kegogi'],
    'Kitutu Chache South': [
      'Bogusero',
      'Bogeka',
      'Nyakoe',
      'Kitutu Central',
      'Nyatieko',
    ],
    'Nyaribari Chache': [
      'Birongo',
      'Nyaribari Central',
      'Keumbu',
      'Kiogoro',
      'Ibeno',
    ],
    'Nyaribari Masaba': ['Masimba', 'Gesusu', 'Kiamokama', 'Moticho'],
    'Bobasi': [
      'Masige East',
      'Masige West',
      'Basi Central',
      'Nyacheki',
      'Bassi Bogetaorio',
      'Bassi Chache',
      'Sameta/Mokwerero',
      'Bobasi Boitangare',
      'Bobasi Chache',
    ],
    'Bomachoge Borabu': [
      'Magenche',
      'Boochi Borabu',
      'Boochi/Tendere',
      'Bombaba Borabu',
    ],
    'Bomachoge Chache': ['Majoge Basi', 'Boochi/Tendere', 'Bombaba'],
    'South Mugirango': [
      'Tabaka',
      'Boikanga',
      'Bogetenga',
      'Borabu Masaba',
      'Moticho',
      'Getenga',
    ],
    'North Mugirango': ['Bomwagamo', 'Bokeira', 'Magwagwa', 'Ekerenyo'],
  },
  'Kisumu': {
    'Kisumu Central': [
      'Railways',
      'Migosi',
      'Shaurimoyo Kaloleni',
      'Market Milimani',
      'Nyalenda A',
      'Nyalenda B',
    ],
    'Kisumu East': [
      'Kajulu',
      'Kolwa East',
      'Manyatta B',
      'Nyalenda A',
      'Kolwa Central',
    ],
    'Kisumu West': [
      'South West Kisumu',
      'Central Kisumu',
      'West Kisumu',
      'North West Kisumu',
    ],
    'Muhoroni': ['Ombeyi', 'Masogo/Nyang’oma', 'Chemelil', 'Muhoroni/Koru'],
    'Nyakach': [
      'South East Nyakach',
      'North Nyakach',
      'Central Nyakach',
      'West Nyakach',
    ],
    'Nyando': [
      'Ahero',
      'Awasi/Onjiko',
      'Kobura',
      'East Kano/Wawidhi',
      'Kabonyo/Kanyagwal',
    ],
    'Seme': ['West Seme', 'Central Seme', 'East Seme', 'North Seme'],
  },

  'Kitui': {
    'Kitui West': ['Mutonguni', 'Kauwi', 'Ma', 'Kwanutonga'],
    'Kitui Central': [
      'Miambani',
      'Township',
      'Kyangwithya West',
      'Mulango',
      'Kwangwithya East',
    ],
    'Kitui Rural': ['Kisasi', 'Mbitini', 'Kwavonza/ Yatta', 'Kanyangi'],
    'Kitui South': [
      'Ikanga/Kyatune',
      'Mutomo',
      'Mutha',
      'Ikutha',
      'Kanziko',
      'Athi',
    ],
    'Kitui East': [
      'Zombe/Mwitika',
      'Nzambani',
      'Chuluni',
      'Voo/Kyamtu',
      'Enda/Malalani',
      'Mutitu/Kaliku',
    ],
    'Mwingi North': ['Ngomeni', 'Kyuso', 'Mumoni', 'Tsei/Kuru', 'Tharaka'],
    'Mwingi West': ['Kyome/Thaana', 'Nguutani', 'Migwani', 'Kiomo/Kyethani'],
    'Mwingi Central': [
      'Nguni',
      'Nguutani',
      'Mui',
      'Central',
      'Kivou',
      'Kyangwithya West',
      'Kyangwithya East',
    ],

    'Mwingi East': ['Kivou', 'Nguni', 'Nuu', 'Mui', 'Waita'],
  },
  'Kwale': {
    'Kinango': [
      'Ndavaya',
      'Puma',
      'Kinango',
      'Mackinon Road',
      'Chengoni / Samburu',
      'Mwavumbo',
      'Kasemeni',
    ],
    'Lunga Lunga': ['Pongwe/Kikomeni', 'Dzombo', 'Mwereni', 'Vanga'],
    'Msambweni': ['Gombato Bongwe', 'Ukunda', 'Kinondo', 'Ramisi'],
    'Matuga': ['Tsimba Golini', 'Waa', 'Tiwi', 'Kubo South', 'Mkongani'],
  },
  'Laikipia': {
    'Laikipia Central': ['Ngobit', 'Tigithi', 'Thingithu', 'Nanyuki', 'Umande'],
    'Laikipia East': ['Segera', 'Ngobit', 'Tigithi', 'Thingithu', 'Umande'],
    'Laikipia North': ['Mukogondo West', 'Mukogondo East'],
    'Laikipia West': [
      'Ol-Moran',
      'Rumuruti Township',
      'Githiga',
      'Marmanet',
      'Sipili',
    ],
    'Nyahururu': ['Igwamiti', 'Salama', 'Gathanji', 'Gatimu', 'Weru'],
  },
  'Lamu': {
    'Lamu East': ['Faza', 'Kiunga', 'Basuba'],
    'Lamu West': [
      'Shella',
      'Mkomani',
      'Hindi',
      'Mkunumbi',
      'Hongwe',
      'Witu',
      'Bahari',
    ],
  },
  'Machakos': {
    'Kathiani': ['Mitaboni', 'Kathiani Central', 'Upper Kaewa', 'Lower Kaewa'],
    'Machakos Town': [
      'Kalama',
      'Mua',
      'Mutituni',
      'Machakos Central',
      'Mumbuni North',
      'Muvuti/Kiima-Kimwe',
      'Kola',
    ],
    'Masinga': [
      'Kivaa',
      'Masinga Central',
      'Ekalakala',
      'MMuthesya',
      'Ndithini',
    ],
    'Matungulu': [
      'Tala',
      'Matungulu North',
      'Matungulu East',
      'Matungulu West',
      'Kyeleni',
    ],
    'Mavoko': ['Athi River', 'Kiname', 'Muthwani', 'Syokimau', 'Mulolongo'],
    'Mwala': [
      'Mbiuni',
      'Makutano',
      'Masii',
      'Muthetheni',
      'Wamunyu',
      'Kibauni',
    ],
    'Yatta': ['Ndalani', 'Matuu', 'Kithimani', 'Ikombe', 'Katangi'],
    'Kangundo': [
      'Kang`undo North',
      'Kang`undo Central',
      'Kang`undo East',
      'Kang`undo West',
    ],
  },
  'Makueni': {
    'Kaiti': ['Ukia', 'Kee', 'Kilungu', 'Ilima'],
    'Kibwezi West': [
      'Makindu',
      'Nguumo',
      'Kikumbulyu North',
      'Kikumbulyu South',
      'Nguu/Masumba',
      'Emali/Mulala',
    ],
    'Kibwezi East': [
      'Masongaleni',
      'Mtito Andei',
      'Thange',
      'Ivingoni/Nzambani',
    ],
    'Kilome': ['Kasikeu', 'Mukaa', 'Kiima Kiu/Kalanzoni'],
    'Makueni': [
      'Wote',
      'Muvau/Kikuumini',
      'Mavindini',
      'Kitise/Kithuki',
      'Kathonzweni',
      'Nzaui/Kilili/Kalamba',
    ],
    'Mbooni': [
      'Tulimani',
      'Mbooni',
      'Kithungo/Kitundu',
      'Kisau/Kiteta',
      'Waia/Kako',
      'Kalawa',
    ],
  },
  'Mandera': {
    'Banissa': ['Banissa', 'Derkhale', 'Guba', 'Malkamari', 'Kiliwehiri'],
    'Lafey': ['Sala', 'Fino', 'Lafey', 'Warahqara', 'Alungo'],
    'Mandera East': ['Arabia', 'Libehia', 'Khalalio', 'Neboi', 'Township'],
    'Mandera North': [
      'Ashabito',
      'Guticha',
      'Marothile',
      'Rhamu',
      'Rhamu Dimtu',
    ],
    'Mandera South': [
      'Wargadud',
      'Kutulo',
      'Elwak South',
      'Elwak North',
      'Shimbir Fatuma',
    ],
    'Mandera West': ['Takaba South', 'Takaba', 'Lagsure', 'Dandu', 'Gither'],
  },
  'Marsabit': {
    'Laisamis': [
      'Loiyangalani',
      'Kargi',
      'Korr Ngurumi',
      'Logologo',
      'Laisamus',
    ],
    'Moyale': [
      'Butiye',
      'Sololo',
      'Heillu/Manyatta',
      'Golbo',
      'Moyale Township',
      'Uran',
      'Obbu',
    ],
    'North Horr': ['Dukana', 'Maikona', 'Turbi', 'North Horr', 'Illeret'],
    'Saku': ['Sagante/Jaldesa', 'Karare', 'Marsabit Central'],
  },
  'Meru': {
    'Buuri': ['Timau', 'Kisima', 'Kiirua', 'Naari', 'Ruiri', 'Rwarera'],
    'Igembe Central': [
      'Akirangondu',
      'Athiru Ruujine',
      'Igembe East',
      'Njia',
      'Kangeta',
    ],
    'Igembe North': [
      'Antuambui',
      'Ntunene',
      'Antubetwe Kiongo',
      'Naathu',
      'Amwathi',
    ],
    'Igembe South': [
      'Mitunguu',
      'Igoji East',
      'Igoji West',
      'Abogeta East',
      'Abogeta West',
      'Nkuene',
    ],
    'Imenti Central': [
      'Mwanganthia',
      'Abothuguchi Central',
      'Abothuguchi West',
      'Kiagu',
      'Kibirichia',
    ],
    'Imenti North': [
      'Municipality',
      'Ntima East',
      'Ntima West',
      'Nyaki West',
      'Nyaki East',
    ],
    'Imenti South': [
      'Maua',
      'Kiegoi/Antubochiu',
      'Athiru Gaiti',
      'Akachiu',
      'Kanuni',
    ],
    'Tigania East': ['Thangatha', 'Mikinduri', 'Kiguchwa', 'Muthara', 'Karama'],
    'Tigania West': ['Athwana', 'Akithii', 'Kianjai', 'Nkomo', 'Mbeu'],
  },
  'Migori': {
    'Awendo': ['North Sakwa', 'South Sakwa', 'West Sakwa', 'Central Sakwa'],
    'Kuria East': [
      'Gokeharaka/Getambwega',
      'Ntimaru West',
      'Ntimaru East',
      'Nyabasi East',
      'Nyabasi West',
    ],
    'Kuria West': [
      'Bukira East',
      'Bukira Cent./Ikerege',
      'Isibania',
      'Makerero',
      'Masaba',
      'Tagare',
      'Nyamosense/Komosoko',
    ],
    'Mabera': ['Kakurikit', 'Ikerege', 'Nyamosense', 'Komosoko'],
    'Ntimaru': ['Ntimaru East', 'Ntimaru West', 'Nyabasi East', 'Nyabasi West'],
    'Rongo': [
      'North Kamagambo',
      'Central Kamagambo',
      'East Kamagambo',
      'South Kamagambo',
    ],
    'Suna East': ['God Jope', 'Suna Central', 'Kakrao'],
    'Suna West': ['Wiga', 'Wasweta II', 'Ragana-Oruba', 'Marabu'],
    'Uriri': [
      'West Kanyamkago',
      'North Kanyamkago',
      'Central Kanyamkago',
      'South Kanyamkago',
      'East Kanyamkago',
    ],
  },
  'Mombasa': {
    'Changamwe': ['Port Reitz', 'Kipevu', 'Airport', 'Miritini', 'Chaani'],
    'Jomvu': ['Jomvu Kuu', 'Magongo', 'Mikindani'],
    'Kisauni': [
      'Mjambere',
      'Junda',
      'Bamburi',
      'Mwakirunge',
      'Mtopanga',
      'Magogori',
      'Shanzu',
    ],
    'Likoni': ['Mtongwe', 'Shika Adabu', 'Bofu', 'Likoni'],
    'Mvita': [
      'Mji Wa Kale/Makadara',
      'Tudor',
      'Tononoka',
      'Shimanzi/Ganjoni',
      'Majengo',
    ],
    'Nyali': [
      'Frere Town',
      'Ziwa La Ngombe',
      'Mkomani',
      'Kongowea',
      'Kadzandani',
    ],
  },
  'Murang’a': {
    'Gatanga': [
      'Ithanga',
      'Kakuzi/Mitubiri',
      'Mugumo-ini',
      'Kihumbu-ini',
      'Gatanga',
      'Kariara',
    ],
    'Kahuro': ['Mugoiri', 'Mbiri', 'Murarandia', 'Nginda'],
    'Kandara': [
      'Ng’araria',
      'Muruka',
      'Kagundu-ini',
      'Gaichanjiru',
      'Ithiru',
      'Ruchu',
    ],
    'Kangema': ['Kanyenyaini', 'Muguru', 'Rwathia'],
    'Kigumo': ['Kigumo', 'Kangari', 'Kinyona', 'Muthithi'],
    'Kiharu': ['Wangu', 'Mugoiri', 'Mbiri', 'Township', 'Muruka'],
    'Mathioya': ['Gitugi', 'Kamacharia', 'Kiriti'],
    'Murang’a South': ['Makuyu', 'Kamahuha', 'Kambiti', 'Kenol', 'Township'],
  },
  'Nairobi': {
    'Dagoretti North': [
      'Kilimani',
      'Kawangware',
      'Gatina',
      'Kileleshwa',
      'Kabiro',
    ],
    'Dagoretti South': [
      'Mutu-ini',
      'Ngando',
      'Riruta',
      'Uthiru',
      'Ruthimitu',
      'Waithaka',
    ],
    'Embakasi East': [
      'Upper Savannah',
      'Lower Savannah',
      'Embakasi',
      'Utawala',
      'Mihango',
    ],
    'Embakasi North': [
      'Kariobangi North',
      'Dandora Area I',
      'Dandora Area II',
      'Dandora Area III',
      'Dandora Area IV',
    ],
    'Embakasi Central': [
      'Kayole North',
      'Kayole Central',
      'Kayole South',
      'Komarock',
      'Matopeni/Spring Valey',
    ],
    'Embakasi South': [
      'Imara Daima',
      'Kwa Njenga',
      'Kwa Reuben',
      'Pipeline',
      'Kware',
    ],
    'Embakasi West': ['Umoja I', 'Umoja II', 'Mowlem', 'Kariobangi South'],
    'Kamukunji': [
      'Pumwani',
      'Eastleigh North',
      'Eastleigh South',
      'Airbase',
      'California',
    ],
    'Kasarani': ['Clay City', 'Mwiki', 'Kasarani', 'Njiru', 'Ruai'],
    'Kibra': [
      'Laini Saba',
      'Lindi',
      'Makina',
      'Woodley/ Kenya Golf Course',
      'Sarang`mbe',
    ],
    'Lang’ata': [
      'Karen',
      'Nairobi West',
      'Mugumo-in',
      'South-C',
      'Nyayo Highrise',
    ],
    'Makadara': ['Maringo/Hamza', 'Viwandani', 'Harambee', 'Makongeni'],
    'Mathare': [
      'Hospital',
      'Mabatini',
      'Huruma',
      'Ngei',
      'Mlango Kubwa',
      'Kiamaiko',
    ],
    'Roysambu': ['Githurai', 'Kahawa West', 'Zimmerman', 'Roysambu', 'Kahawa'],
    'Ruaraka': [
      'Babadogo',
      'Utalii',
      'Mathare North',
      'Lucky Summer',
      'Korogocho',
    ],
    'Starehe': [
      'Nairobi Central',
      'Ngara',
      'Pangani',
      'Ziwani/ Kariokor',
      'Landimawe',
      'Nairobi South',
    ],
    'Westlands': [
      'Kitusuru',
      'Parklands/Highridge',
      'Karura',
      'Kangemi',
      'Mountain View',
    ],
  },
  'Nakuru': {
    'Bahati': ['Kabazi', 'Bahati', 'Dundori', 'Kabatini', 'Lanet/Umoja'],
    'Gilgil': [
      'Gilgil',
      'Elementaita',
      'Mbaruk/Eburu',
      'Malewa West',
      'Murindati',
    ],
    'Kuresoi North': ['Kiptororo', 'Nyota', 'Sirikwa', 'Kamara'],
    'Kuresoi South': ['Amalo', 'Keringet', 'Kiptagich', 'Tinet'],
    'Molo': ['Mariashoni', 'Elburgon', 'Turi', 'Molo'],
    'Naivasha': [
      'Biashara',
      'Hells Gate',
      'Lakeview',
      'Maiella',
      'Mai Mahiu',
      'Olkaria',
      'Naivasha East',
      'Viwandani',
    ],
    'Nakuru Town East': ['Flamingo', 'Menengai', 'Nakuru East'],
    'Nakuru Town West': [
      'Barut',
      'London',
      'Kaptembwo',
      'Kapkures',
      'Rhoda',
      'Shabab',
    ],
    'Njoro': ['Mauche', 'Kihingo', 'Nessuit', 'Lare', 'Njoro'],
    'Rongai': ['Menengai West', 'Soin', 'Visoi', 'Mosop', 'Solai'],
    'Subukia': ['Kabazi', 'Subukia', 'Waseges'],
  },
  'Nandi': {
    'Aldai': [
      'Kabwareng',
      'Kaptumo/Kaboi',
      'Koyo/Ndurio',
      'Kemeloi-Maraba',
      'Kobujoi',
      'Kaptel/Kamoiywo',
    ],
    'Chesumei': [
      'Chemundu/Kapng’etuny',
      'Kosirai',
      'Lelmokwo/Ngechek',
      'Kaptel/Kapngetuny',
      'Kiptuya',
    ],
    'Emgwen': ['Chepkumia', 'Kapkangani', 'Kapsabet', 'Kilibwoni'],
    'Mosop': [
      'Chepterwai',
      'Kabisaga',
      'Kabiyet',
      'Ndalat',
      'Sangalo/Kebulonik',
      'Kipkaren',
      'Kurgung/Surungai',
    ],
    'Nandi Hills': ['Nandi Hills', 'Chepkunyuk', 'Ol’lessos', 'Kapchorua'],
    'Tindiret': ['Songhor/Soba', 'Tindiret', 'Chemelil/Chemase', 'Kapsimotwo'],
  },
  'Narok': {
    'Narok East': ['Mosiro', 'Keekonyokie', 'Suswa', 'Ilmeshuki'],
    'Narok North': [
      'Olorropil',
      'Olokurto',
      'Narok Town',
      'Nkareta',
      'Olposimoru',
      'Melili',
    ],
    'Narok South': [
      'Majimoto/Naroosura',
      'Ololulung’a',
      'Melelo',
      'Loita',
      'Sogoo',
      'Sagamian',
    ],
    'Narok West': ['Ilmotiok', 'Mara', 'Siana', 'Naikarra'],
    'Transmara East': ['Ilkerin', 'Ololmasani', 'Mogondo', 'Kapsasian'],
    'Transmara West': [
      'Kilgoris Central',
      'Keyian',
      'Angata Barikoi',
      'Shankoe',
      'Kimintet',
      'Lolgorian',
    ],
  },
  'Nyamira': {
    'Borabu': ['Esise', 'Nyansiongo', 'Kiabonyoru', 'Mekenene'],
    'Manga': ['Manga', 'Gesima', 'Nyaura'],
    'Masaba North': ['Rigoma', 'Gachuba', 'Kemera', 'Magombo'],
    'Nyamira North': [
      'Ekerenyo',
      'Magwagwa',
      'Bokeira',
      'Bomwagamo',
      'Mugirango West',
    ],
    'Nyamira South': ['Bogichora', 'Bosamaro', 'Bonyamatuta', 'Nyamaiya'],
  },
  'Nyandarua': {
    'Kinangop': [
      'Engineer',
      'Githabai',
      'Githioro',
      'North Kinangop',
      'Murungaru',
      'Njabini/Kiburu',
      'Nyakio',
      'Kipipiri',
    ],
    'Kipipiri': ['Malewa West', 'Kipipiri', 'Geta', 'Wanjohi'],
    'Ndaragwa': ['Leshau Pondo', 'Kiriita', 'Central', 'Shamata'],
    'Ol-Kalou': ['Karau', 'Kanjuiri Range', 'Mirangine', 'Kaimbaga', 'Rurii'],
    'Ol Joro Orok': ['Gathanji', 'Gatimu', 'Weru', 'Charagita'],
  },
  'Nyeri': {
    'Kieni East': [
      'Naromoru/Kiamathaga',
      'Mwiyogo/Endarasha',
      'Mweiga',
      'Mugunda',
      'Gatarakwa',
      'Thegu River',
    ],
    'Kieni West': [
      'Mukurweini West',
      'Kabaru',
      'Gakawa',
      'Kirimukuyu',
      'Kieni',
    ],
    'Mathira East': ['Magutu', 'Iriani', 'Kirimukuyu', 'Karatina Town'],
    'Mathira West': ['Ruguru', 'Magutu', 'Iriani', 'Karatina Town'],
    'Mukurweini': ['Gikondi', 'Rugi', 'Mukure', 'Githi'],
    'Nyeri Town': [
      'Kiganjo/Mathari',
      'Ruring’u',
      'Kamakwa/Mukaro',
      'Gatitu/Muruguru',
      'Rware',
    ],
    'Othaya': ['Iria-Ini', 'Chinga', 'Karima', 'Mahiga'],
    'Tetu': ['Dedan Kimathi', 'Wamagana', 'Aguthi/Gaaki'],
  },

  'Samburu': {
    'Samburu East': ['Waso', 'Wamba West', 'Wamba East', 'Wamba North'],
    'Samburu North': [
      'El-Barta',
      'Nachola',
      'Ndoto',
      'Nyiro',
      'Angata Nanyekie',
      'Baawa',
    ],
    'Samburu West': ['Lodokejek', 'Suguta Marmar', 'Maralal', 'Loosuk', 'Poro'],
  },
  'Siaya': {
    'Alego Usonga': [
      'Usonga',
      'West Alego',
      'Central Alego',
      'Siaya Township',
      'North Alego',
      'South East Alego',
    ],
    'Bondo': [
      'West Yimbo',
      'Central Sakwa',
      'South Sakwa',
      'Yimbo East',
      'West Sakwa',
    ],
    'Gem': [
      'North Gem',
      'West Gem',
      'Central Gem',
      'Yala Township',
      'East Gem',
    ],
    'Rarieda': [
      'West Asembo',
      'East Asembo',
      'North Uyoma',
      'South Uyoma',
      'West Uyoma',
    ],
    'Ugenya': ['West Ugenya', 'North Ugenya', 'East Ugenya', 'South Ugenya'],
    'Unguja': ['West Ugunja', 'North Ugunja', 'Sidindi'],
  },

  'Taita-Taveta': {
    'Mwatate': ['Rongo', 'Mwatate', 'Bura', 'Chawia', 'Wusi/Kishamba'],
    'Taveta': ['Chala', 'Mahoo', 'Bomani', 'Mboghoni', 'Mata'],
    'Voi': ['Mbololo', 'Sagala', 'Kaloleni', 'Marungu', 'Kasigau', 'Ngolia'],
    'Wundanyi': ['Mbale', 'Werugha', 'Wumingu/Kishushe', 'Mwanda/Mgange'],
  },
  'Tana River': {
    'Bura': ['Chewele', 'Hirimani', 'Bangale', 'Sala', 'Madogo'],
    'Galole': ['Kinakomba', 'Mikinduni', 'Chewani', 'Wayu'],
    'Garsen': ['Kipini West', 'Garsen Central', 'Garsen West', 'Garsen North'],
  },
  'Tharaka-Nithi': {
    'Chuka': ['Mariani', 'Karingani', 'Magumoni', 'Mugwe', 'Igambango’mbe'],
    'Maara': ['Mitheru', 'Muthambi', 'Mwimbi', 'Ganga', 'Chogoria'],
    'Tharaka': ['Gatunya', 'Mukothina', 'Nkondi', 'Chiakariga', 'Marimanti'],
  },
  'Trans-Nzoia': {
    'Cherangany': [
      'Makutano',
      'Kaplamai',
      'Motosiet',
      'Cherangany/Suwerwa',
      'Sinyerere',
      'Motosiet',
    ],
    'Endebess': ['Endebess', 'Matumbei', 'Chepchoina'],
    'Kiminini': ['Kiminini', 'Waitaluk', 'Sirende', 'Sikhendu', 'Nabiswa'],
    'Kwanza': ['Kapomboi', 'Kwanza', 'Keiyo', 'Bidii'],
    'Saboti': ['Matisi', 'Tuwani', 'Saboti', 'Machewa', 'Matisi West'],
  },
  'Turkana': {
    'Loima': ['Kotaruk/Lobei', 'Turkwel', 'Loima', 'Lokiriama/Lorengippi'],
    'Turkana Central': [
      'Kanamkemer',
      'Lodwar Township',
      'Kerio Delta',
      'Kang’atotha',
    ],
    'Turkana East': ['Kapedo/Napeitom', 'Katilia', 'Lokori/Kochodin'],
    'Turkana North': [
      'Kaeris',
      'Lake Zone',
      'Lapur',
      'Kaaleng/Kaikor',
      'Kibish',
      'Nakurio',
    ],
    'Turkana South': ['Kaputir', 'Katilu', 'Lobokat', 'Kalapata', 'Lokichar'],
  },

  'Uasin Gishu': {
    'Ainabkoi': ['Kapsoya', 'Kaptagat', 'Ainabkoi/Olare'],
    'Kapseret': ['Simat/Kapseret', 'Kipkenyo', 'Ngeria', 'Megun', 'Langas'],
    'Kesses': ['Racecourse', 'Cheptiret/Kipchamo', 'Tulwet/Chuiyat', 'Tarakwa'],
    'Moiben': ['Tembelio', 'Sergoit', 'Karuna/Meibeki', 'Moiben', 'Kimumu'],
    'Soy': [
      'Moi’s Bridge',
      'Kapkures',
      'Ziwa',
      'Segero/Barsombe',
      'Kipsomba',
      'Soy',
      'Kuinet/Kapsuswa',
    ],
    'Turbo': [
      'Ngenyilel',
      'Tapsagoi',
      'Kamagut',
      'Kiplombe',
      'Huruma',
      'Kapsaos',
    ],
  },
  'Vihiga': {
    'Emuhaya': ['West Bunyore', 'Central Bunyore', 'East Bunyore'],
    'Hamisi': [
      'Shiru',
      'Gisambai',
      'Shamakhokho',
      'Banja',
      'Muhudu',
      'Tambua',
      'Jepkoyai',
    ],
    'Luanda': [
      'Luanda Township',
      'Wemilabi',
      'Mwibona',
      'Luanda South',
      'Emabungo',
    ],
    'Sabatia': [
      'Lyaduywa/Izava',
      'West Sabatia',
      'Chavakali',
      'North Maragoli',
      'Wodanga',
      'Busali',
    ],
    'Vihiga': [
      'Lugaga-Wamuluma',
      'South Maragoli',
      'Central Maragoli',
      'Mungoma',
    ],
  },

  'Wajir': {
    'Eldas': ['Eldas', 'Della', 'Lakoley South', 'Elnur', 'Basir', 'Tula Tula'],
    'Tarbaj': ['Elben', 'Sannan', 'Tarbaj', 'Wargadud'],
    'Wajir East': [
      'Arbajahan',
      'Hadado Athibool',
      'Ademasajide',
      'Ganyure',
      'Wagalia',
    ],
    'Wajir North': [
      'Gurar',
      'Bute',
      'Korondile',
      'Malkagufu',
      'Batalu',
      'Danaba',
      'Godoma',
    ],
    'Wajir South': [
      'Benane',
      'Burder',
      'Dadaja Bulla',
      'Habaswein',
      'Lagboghol South',
      'Ibrahim Ure',
    ],
    'Wajir West': ['Wagberi', 'Township', 'Barwago', 'Khorof/Harar'],
  },
  'West Pokot': {
    'Central Pokot': ['Sigor', 'Masol', 'Sekerr', 'Mnagei'],
    'North Pokot': ['Alale', 'Kasei', 'Kiwawa', 'Kapchok'],
    'Pokot South': ['Chepareria', 'Batei', 'Lelan', 'Tapach'],
    'West Pokot': ['Kapenguria', 'Mnagei', 'Siyoi', 'Riwo', 'Endugh'],
  },
};
